name: Build, Push and Deploy

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 3: Build and Push Backend Image
      - name: Build and Push Backend Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/be-todo:latest ./practical1/todo-app/backend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/be-todo:latest

      # Step 4: Build and Push Frontend Image
      - name: Build and Push Frontend Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/fe-todo:latest ./practical1/todo-app/frontend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/fe-todo:latest

      # Step 5: Trigger Render Backend Redeployment
      - name: Trigger Render Backend Deploy
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_BACKEND }}

      # Step 6: Trigger Render Frontend Redeployment
      - name: Trigger Render Frontend Deploy
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_FRONTEND }}